version: '3.5'

services: 
  backend:
    image: backend
    environment: 
      - REDIS_HOST=redis
    ports: 
      - 8080:8080
  frontend: 
    image: frontend
    ports: 
      - 5000:5000
  redis:
    image: redis