version: '3.5'

services:
  front:
    image: mopofront
    ports:
      - 3000:3000
  back:
    image: mopoback
    volumes:
      - vol1:/src/model
    ports:
      - 5000:5000
    depends_on: 
      - training
  training:
    image: mopotraining
    volumes:
      - vol1:/src/model
      - vol2:/src/imgs

volumes:
  vol1:
  vol2:
